POST {{host}}
Content-Type: application/json
Accept: application/json
X-Gitlab-Token: 123

{
  "object_kind": "push",
  "event_name": "push",
  "before": "ef655435039f7bb67bd891309d3e288a0ff3cd26",
  "after": "50b9bbd36f82c66bc830074cf10c3824cfe5f2bc",
  "ref": "refs/heads/master",
  "checkout_sha": "50b9bbd36f82c66bc830074cf10c3824cfe5f2bc",
  "message": null,
  "user_id": 4338300,
  "user_name": "Vladimir Rebo",
  "user_username": "vladimir.safonov",
  "user_email": "safonov.open@gmail.com",
  "user_avatar": "https://secure.gravatar.com/avatar/b68b6d7b8e7c1333868ecfb70ea6ec10?s=80&d=identicon",
  "project_id": 30217351,
  "project": {
    "id": 30217351,
    "name": "RocketAuth",
    "description": "",
    "web_url": "https://gitlab.com/vladimir.safonov/rocketauth",
    "avatar_url": null,
    "git_ssh_url": "git@gitlab.com:vladimir.safonov/rocketauth.git",
    "git_http_url": "https://gitlab.com/vladimir.safonov/rocketauth.git",
    "namespace": "Vladimir Rebo",
    "visibility_level": 0,
    "path_with_namespace": "vladimir.safonov/rocketauth",
    "default_branch": "master",
    "ci_config_path": "",
    "homepage": "https://gitlab.com/vladimir.safonov/rocketauth",
    "url": "git@gitlab.com:vladimir.safonov/rocketauth.git",
    "ssh_url": "git@gitlab.com:vladimir.safonov/rocketauth.git",
    "http_url": "https://gitlab.com/vladimir.safonov/rocketauth.git"
  },
  "commits": [
    {
      "id": "50b9bbd36f82c66bc830074cf10c3824cfe5f2bc",
      "message": "Update .gitignore",
      "title": "Update .gitignore",
      "timestamp": "2021-12-08T07:24:39+00:00",
      "url": "https://gitlab.com/vladimir.safonov/rocketauth/-/commit/50b9bbd36f82c66bc830074cf10c3824cfe5f2bc",
      "author": {
        "name": "Vladimir Rebo",
        "email": "safonov.open@gmail.com"
      },
      "added": [
      ],
      "modified": [
        ".gitignore"
      ],
      "removed": [
      ]
    }
  ],
  "total_commits_count": 1,
  "push_options": {
  },
  "repository": {
    "name": "RocketAuth",
    "url": "git@gitlab.com:vladimir.safonov/rocketauth.git",
    "description": "",
    "homepage": "https://gitlab.com/vladimir.safonov/rocketauth",
    "git_http_url": "https://gitlab.com/vladimir.safonov/rocketauth.git",
    "git_ssh_url": "git@gitlab.com:vladimir.safonov/rocketauth.git",
    "visibility_level": 0
  }
}
